#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Create Spring Boot Classes via CLI', '1.0.0');

$commands = [
	\NasrulHazim\Console\Commands\MakeControllerCommand::class,
	\NasrulHazim\Console\Commands\MakeModelCommand::class,
];

foreach ($commands as $command) {
	$app->add((new $command));
}

$app->run();